spring:
  jpa:
    hibernate:
     ddl-auto: update
     naming: 
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false  
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/access
    username: sabis
    password: sabis
thymeleaf:
  enabled: true
  cache: false
  check-template: true
  check-template-location: true
  servlet:
   content-type: text/html
  encoding: UTF-8
  prefix: classpath:/templates/
  suffix: .html                 
logging:
  pattern:
    console: "%d{dd/MM/yyyy HH:mm:ss} %-5p %c{1}:%L - %m%n"
    file: "%d{dd/MM/yyyy HH:mm:ss} %-5p %c{1}:%L - %m%n"
  level:
    root: INFO
    web: INFO
    sql: INFO
  file: 
    name: "C:\\User\\logs\\pcasabis.log"  
server:
  port: 8001
  servlet:
    session:
      timeout: 7200 
charset:
  force: false
  value: ISO-8859-1   
  
security:
  oauth2:
    client:
      client-secret: 123
      client-id: teste
      scope: password     